# Site wide configuration

title: milmazz
locale: en-US
description: "To teach is to learn twice. - Joseph Joubert"
#logo: site-logo.png
url: https://milmazz.uno

# Jekyll configuration
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Chicago
encoding: utf-8
permalink: /article/:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge
remote_theme: "mmistakes/so-simple-theme"
skin: "/assets/css/skins/dark.css"

## read time
read_time: true
words_per_minute: 200

## mathematics
mathjax: false

## Pagination
paginate: 5
paginate_path: /page:num/

## Full Text Search support
# Disabled, it could affect page load performance
search_full_content: false

excerpt_separator: <!--more-->

# taxonomy pages
tag_archive_path: "/tags/#"
category_archive_path: "/categories/#"

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-github-metadata

# Collections
collections:
  talks:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: true
  # Talks collection
  - scope:
      path: "_talks"
      type: talks
    values:
      layout: post
      comments: false
      share: true

## Google Fonts
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

liquid:
  error_mode: strict

feed:
  path: atom.xml

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md

# Site owner
author:
  name: Milton Mazzarri
  picture: /images/milmazz.png
  email: me@milmazz.uno
  twitter: milmazz
  links:
    - title: GitHub
    - url: https://github.com/milmazz
    - icon: fab fa-github-square

footer_links:
  - title: Twitter
    url: https://twitter.com/milmazz
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/milmazz
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://linkedin.com/in/milmazz
    icon: fab fa-linkedin
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
